title: <p align="center"> Pradeep Hegde </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/pradeep-hegde-a6919aab/">LinkedIn</a> |
  <a href="https://github.com/hegde-23">GitHub</a>
  
  <br>   
  I'm working on Data Science, Big Data, Spark, Machine learning & NLP related problems.
  <br>
  </p>
  
  
  
  
  
  theme: jekyll-theme-minimal
